npmPublishAccess: public

npmScopes:
  dmeents:
    npmAuthToken: "${NPM_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@latest"
      "#supports-color": "npm:supports-color@latest"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
