name: 'Release Standard'
description: 'standardized release job'

inputs:
  packageName:
    description: 'the package to build'
    required: true
  nodeVersion:
    description: 'which node version to use'
    required: false
    default: 'latest'
  namespace:
    description: 'the monorepo namespace'
    required: false
    default: 'undefined'
  npmToken:
    description: 'the npm token to publish packages to npm'
    required: true
  githubToken:
    description: 'the github token required to push package changes to github'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup Yarn Caching
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'yarn'

    - name: Get built artifact
      if: ${{ inputs.namespace == 'undefined' }}
      uses: actions/download-artifact@master
      with:
        name: ${{ inputs.packageName }}-build-${{ github.sha }}
        path: .dist

    - name: Get built artifact for ${{ inputs.packageName }} in monorepo
      if: ${{ inputs.namespace != 'undefined' }}
      uses: actions/download-artifact@master
      with:
        name: ${{ inputs.packageName }}-build-${{ github.sha }}
        path: packages/${{ inputs.packageName }}/.dist

    - name: Release Package
      shell: bash
      run: |
        NPM_TOKEN=${{ inputs.npmToken }} GH_TOKEN=${{ inputs.githubToken }} yarn publish
