name: 'Build Standard'
description: 'standardized build job'
author: 'david@allido.io'

inputs:
  packageName:
    description: 'the package to build'
    required: true
  nodeVersion:
    description: 'which node version to use'
    required: false
    default: 'latest'
  namespace:
    description: 'the monorepo namespace'
    required: false
    default: 'undefined'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup Yarn
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'yarn'

    - name: Yarn Install
      shell: bash
      run: yarn install

    - name: Build ${{ inputs.packageName }}
      if: ${{ inputs.namespace == 'undefined' }}
      shell: bash
      run: yarn build

    - name: Build ${{ inputs.packageName }} in monorepo
      if: ${{ inputs.namespace != 'undefined' }}
      shell: bash
      run: yarn workspace ${{ inputs.namespace }}/${{ inputs.packageName }} build

    - name: Save build artifact
      uses: actions/upload-artifact@master
      if: ${{ inputs.namespace == 'undefined' }}
      with:
        if-no-files-found: ignore
        name: ${{ inputs.packageName }}-build-${{ github.sha }}
        path: .dist

    - name: Save build artifact for ${{ inputs.packageName }} in monorepo
      uses: actions/upload-artifact@master
      if: ${{ inputs.namespace != 'undefined' }}
      with:
        if-no-files-found: ignore
        name: ${{ inputs.packageName }}-build-${{ github.sha }}
        path: packages/${{ inputs.packageName }}/.dist
