name: 'Build Standard'
description: 'standardized build job'

inputs:
  packageName:
    description: 'the package to build'
    required: true
  nodeVersion:
    description: 'which node version to use'
    required: false
    default: 'latest'
  isMonorepo:
    description: 'is project a monorepo?'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup Yarn Caching
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'yarn'

    - name: Yarn Install
      shell: bash
      run: yarn install

    - name: Build ${{ inputs.packageName }}
      if: ${{ inputs.isMonorepo == false }}
      shell: bash
      run: yarn build

    - name: Build package ${{ inputs.packageName }}
      if: ${{ inputs.isMonorepo == true }}
      shell: bash
      run: yarn workspace ${{ inputs.packageName }} build

    - name: Save build artifact
      uses: actions/upload-artifact@master
      with:
        if-no-files-found: ignore
        name: ${{ inputs.packageName }}-build-${{ github.sha }}
        path: .dist
