name: 'Test Standard'
description: 'standardized test job'
author: 'david@allido.io'

inputs:
  testSuite:
    description: 'the test suite to run'
    required: true
  nodeVersion:
    description: 'which node version to use'
    required: false
    default: 'latest'
  codeCovSecret:
    description: 'the secret for codecov'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup Yarn
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'yarn'

    - name: Yarn Install
      shell: bash
      run: yarn install

    - name: Run tests
      if: ${{ inputs.testSuite == 'jest' }}
      shell: bash
      run: yarn test:coverage

    - name: Upload coverage reports to Codecov
      if: ${{ inputs.testSuite == 'jest' }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codeCovSecret }}
