name: 'Test Standard'
description: 'standardized test job'
author: 'david@allido.io'

inputs:
  testSuite:
    description: 'the test suite to run'
    required: true
  nodeVersion:
    description: 'which node version to use'
    required: false
    default: 'latest'
  codeCovSecret:
    description: 'the secret for codecov'
    required: false
  npmToken:
    description: 'the npm token'
    required: false
  foresightToken:
    description: 'the foresight token'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup Yarn
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'yarn'

    - name: Yarn Install
      shell: bash
      run: yarn install

    - name: Run tests
      if: ${{ inputs.testSuite == 'jest' }}
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npmToken }}
      run: yarn test:coverage

    - name: Upload Coverage to Foresight
      uses: runforesight/foresight-test-kit-action@v1
      if: ${{ inputs.testSuite == 'jest' }}
      with:
        api_key: inputs.foresightToken
        test_format: JUNIT
        test_framework: JEST
        coverage_format: JACOCO/XML
        coverage_path: ./junit.xml

    - name: Upload coverage reports to Codecov
      if: ${{ inputs.testSuite == 'jest' }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codeCovSecret }}
