name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Package
        uses: ./src/github-actions/build-standard
        with:
          packageName: 'maestro'

  #  test runs after build in maestro so it can have the built jest config to use
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        suite: [ 'jest' ]
    steps:
      - uses: actions/checkout@v3
      - name: Get built artifact
        uses: actions/download-artifact@master
        with:
          name: maestro-build-${{ github.sha }}
          path: .dist
      - name: Test Package
        uses: ./src/github-actions/test-standard
        with:
          testSuite: ${{ matrix.suite }}

  publish:
    runs-on: ubuntu-latest
    needs: [ test ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Publish Package
        uses: ./src/github-actions/release-standard
        with:
          packageName: 'maestro'
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.GH_TOKEN }}
