name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Package
        uses: './src/github-actions/build-standard'
        with:
          packageName: 'maestro'

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Publish Package
        uses: './src/github-actions/release-standard'
        with:
          packageName: 'maestro'
